2018/01/11 22:31:34 [error] 159252#165636: *1 CreateFile() "G:\pyWorkspace\svn\trunk\nginx-1.13.8/MrYangServer/static/media/110.mp4" failed (3: The system cannot find the path specified), client: 192.168.1.226, server: localhost, request: "GET /110.mp4 HTTP/1.1", host: "192.168.1.226", referrer: "http://localhost:909/"
2018/01/11 22:31:34 [error] 159252#165636: *1 CreateFile() "G:\pyWorkspace\svn\trunk\nginx-1.13.8/html/favicon.ico" failed (2: The system cannot find the file specified), client: 192.168.1.226, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.1.226"
2018/01/11 22:31:34 [error] 159252#165636: *1 CreateFile() "G:\pyWorkspace\svn\trunk\nginx-1.13.8/html/favicon.ico" failed (2: The system cannot find the file specified), client: 192.168.1.226, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.1.226"
2018/01/11 22:31:53 [notice] 147888#150164: signal process started
2018/01/12 19:42:38 [error] 158224#109512: *20 CreateFile() "G:\pyWorkspace\svn\trunk\nginx-1.13.8/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1"
2018/01/12 21:02:52 [error] 158224#109512: *22 CreateFile() "G:\pyWorkspace\svn\trunk\nginx-1.13.8/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "127.0.0.1"
2018/01/17 12:50:13 [emerg] 12192#8196: unknown directive "rtmp" in G:\pyWorkspace\svn\trunk\nginx-1.13.8/conf/nginx.conf:15
2018/01/17 12:50:33 [emerg] 12932#8372: unknown directive "rtmp" in G:\pyWorkspace\svn\trunk\nginx-1.13.8/conf/nginx.conf:15
2018/01/17 12:52:01 [emerg] 11992#4664: unknown directive "rtmp_stat" in G:\pyWorkspace\svn\trunk\nginx-1.13.8/conf/nginx.conf:70
2018/01/17 12:58:24 [emerg] 11532#880: unknown directive "rtmp" in G:\pyWorkspace\svn\trunk\nginx-1.13.8/conf/nginx.conf:15
2018/01/17 13:05:18 [emerg] 9924#14032: unknown directive "rtmp" in G:\pyWorkspace\svn\trunk\nginx-1.13.8/conf/nginx.conf:15
2018/01/17 13:11:54 [emerg] 15064#3256: unknown directive "rtmp" in G:\pyWorkspace\svn\trunk\nginx-1.13.8/conf/nginx.conf:15
2018/01/17 13:12:02 [emerg] 14952#15232: unknown directive "rtmp" in G:\pyWorkspace\svn\trunk\nginx-1.13.8/conf/nginx.conf:15
2018/01/17 13:12:10 [notice] 12324#10652: signal process started
2018/01/17 13:12:10 [error] 12324#10652: OpenEvent("Global\ngx_stop_160540") failed (2: The system cannot find the file specified)
2018/05/29 18:14:40 [emerg] 175992#176004: CreateDirectory() "G:\pyWorkspace\django_work\nginx-1.13.8/temp/client_body_temp" failed (3: The system cannot find the path specified)
2018/05/29 18:14:42 [emerg] 174832#173936: CreateDirectory() "G:\pyWorkspace\django_work\nginx-1.13.8/temp/client_body_temp" failed (3: The system cannot find the path specified)
2018/05/29 18:15:12 [error] 176108#142648: *1 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost"
2018/05/29 18:15:12 [error] 176108#142648: *1 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost"
2018/05/29 18:20:26 [error] 176108#142648: *5 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/000.ts" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/000.ts HTTP/1.1", host: "localhost"
2018/05/29 18:20:26 [error] 176108#142648: *6 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/000.ts" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/000.ts HTTP/1.1", host: "localhost"
2018/05/29 18:20:26 [error] 176108#142648: *7 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/000.ts" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/000.ts HTTP/1.1", host: "localhost"
2018/05/29 18:20:26 [error] 176108#142648: *8 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/000.ts" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/000.ts HTTP/1.1", host: "localhost"
2018/05/29 18:20:26 [error] 176108#142648: *9 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/000.ts" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/000.ts HTTP/1.1", host: "localhost"
2018/05/29 18:21:51 [error] 176108#142648: *12 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/000.ts" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/000.ts HTTP/1.1", host: "localhost"
2018/05/29 18:21:51 [error] 176108#142648: *13 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/000.ts" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/000.ts HTTP/1.1", host: "localhost"
2018/05/29 18:21:51 [error] 176108#142648: *14 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/000.ts" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/000.ts HTTP/1.1", host: "localhost"
2018/05/29 18:21:51 [error] 176108#142648: *15 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/000.ts" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/000.ts HTTP/1.1", host: "localhost"
2018/05/29 18:21:52 [error] 176108#142648: *16 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/000.ts" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/000.ts HTTP/1.1", host: "localhost"
2018/05/29 19:08:51 [warn] 173660#174616: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:08:51 [warn] 173660#174616: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:08:51 [warn] 177204#176724: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:08:51 [warn] 177204#176724: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:10:24 [warn] 178140#129632: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:10:24 [warn] 178140#129632: duplicate extension "m3u8", content type: "application/vnd.apple.mpegurl", previous content type: "application/x-mpegURL" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:10:24 [warn] 178140#129632: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:97
2018/05/29 19:10:24 [warn] 176032#177760: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:10:24 [warn] 176032#177760: duplicate extension "m3u8", content type: "application/vnd.apple.mpegurl", previous content type: "application/x-mpegURL" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:10:24 [warn] 176032#177760: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:97
2018/05/29 19:11:02 [warn] 176924#177748: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:11:02 [warn] 176924#177748: duplicate extension "m3u8", content type: "application/vnd.apple.mpegurl", previous content type: "application/x-mpegURL" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:11:02 [warn] 176924#177748: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:97
2018/05/29 19:11:02 [warn] 177716#174112: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:11:02 [warn] 177716#174112: duplicate extension "m3u8", content type: "application/vnd.apple.mpegurl", previous content type: "application/x-mpegURL" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:11:02 [warn] 177716#174112: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:97
2018/05/29 19:11:04 [warn] 175384#173700: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:11:04 [warn] 175384#173700: duplicate extension "m3u8", content type: "application/vnd.apple.mpegurl", previous content type: "application/x-mpegURL" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:11:04 [warn] 175384#173700: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:97
2018/05/29 19:11:04 [notice] 175384#173700: signal process started
2018/05/29 19:11:07 [warn] 176916#129008: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:11:07 [warn] 176916#129008: duplicate extension "m3u8", content type: "application/vnd.apple.mpegurl", previous content type: "application/x-mpegURL" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:11:07 [warn] 176916#129008: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:97
2018/05/29 19:11:08 [warn] 177780#167820: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:11:08 [warn] 177780#167820: duplicate extension "m3u8", content type: "application/vnd.apple.mpegurl", previous content type: "application/x-mpegURL" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:11:08 [warn] 177780#167820: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:97
2018/05/29 19:11:45 [error] 176108#142648: *22 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/000.ts" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/000.ts HTTP/1.1", host: "localhost"
2018/05/29 19:11:45 [error] 176108#142648: *23 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/000.ts" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/000.ts HTTP/1.1", host: "localhost"
2018/05/29 19:11:45 [error] 176108#142648: *24 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/000.ts" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/000.ts HTTP/1.1", host: "localhost"
2018/05/29 19:11:45 [error] 176108#142648: *25 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/000.ts" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/000.ts HTTP/1.1", host: "localhost"
2018/05/29 19:11:45 [error] 176108#142648: *26 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/000.ts" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/000.ts HTTP/1.1", host: "localhost"
2018/05/29 19:13:45 [warn] 174552#176752: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:13:45 [warn] 174552#176752: duplicate extension "m3u8", content type: "application/vnd.apple.mpegurl", previous content type: "application/x-mpegURL" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:13:45 [warn] 174552#176752: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:97
2018/05/29 19:13:50 [warn] 177504#175816: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:13:50 [warn] 177504#175816: duplicate extension "m3u8", content type: "application/vnd.apple.mpegurl", previous content type: "application/x-mpegURL" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:13:50 [warn] 177504#175816: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:97
2018/05/29 19:14:12 [warn] 169248#177956: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:14:12 [warn] 169248#177956: duplicate extension "m3u8", content type: "application/vnd.apple.mpegurl", previous content type: "application/x-mpegURL" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:14:12 [warn] 169248#177956: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:97
2018/05/29 19:14:16 [warn] 175144#75248: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:14:16 [warn] 175144#75248: duplicate extension "m3u8", content type: "application/vnd.apple.mpegurl", previous content type: "application/x-mpegURL" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:14:16 [warn] 175144#75248: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:97
2018/05/29 19:14:16 [warn] 107560#175360: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:14:16 [warn] 107560#175360: duplicate extension "m3u8", content type: "application/vnd.apple.mpegurl", previous content type: "application/x-mpegURL" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:14:16 [warn] 107560#175360: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:97
2018/05/29 19:14:22 [error] 177504#177348: *1 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/out.m3u8" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/out.m3u8 HTTP/1.1", host: "localhost"
2018/05/29 19:14:22 [error] 177504#177348: *1 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/movie/973e6065ce6a65f4c0d544d540b4580f/out.m3u8"
2018/05/29 19:14:27 [error] 177504#177348: *1 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/out.m3u8" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/out.m3u8 HTTP/1.1", host: "localhost"
2018/05/29 19:15:07 [error] 177504#177348: *1 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/hls/out.m3ub" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /hls/out.m3ub HTTP/1.1", host: "localhost"
2018/05/29 19:19:14 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/out.m3u8" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/out.m3u8 HTTP/1.1", host: "localhost"
2018/05/29 19:19:28 [warn] 177680#176568: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:19:28 [warn] 177680#176568: duplicate extension "m3u8", content type: "application/vnd.apple.mpegurl", previous content type: "application/x-mpegURL" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:19:28 [warn] 177680#176568: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:97
2018/05/29 19:19:29 [warn] 169076#176696: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:19:29 [warn] 169076#176696: duplicate extension "m3u8", content type: "application/vnd.apple.mpegurl", previous content type: "application/x-mpegURL" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:19:29 [warn] 169076#176696: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:97
2018/05/29 19:19:29 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/out.m3u8" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/out.m3u8 HTTP/1.1", host: "localhost"
2018/05/29 19:19:47 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/973e6065ce6a65f4c0d544d540b4580f/out.m3u8" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/973e6065ce6a65f4c0d544d540b4580f/out.m3u8 HTTP/1.1", host: "localhost"
2018/05/29 19:20:15 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /movie HTTP/1.1", host: "localhost"
2018/05/29 19:20:22 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /movie HTTP/1.1", host: "localhost"
2018/05/29 19:20:25 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /movie HTTP/1.1", host: "localhost"
2018/05/29 19:20:28 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/1.txt" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/1.txt HTTP/1.1", host: "localhost"
2018/05/29 19:20:50 [warn] 177784#177876: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:20:50 [warn] 177784#177876: duplicate extension "m3u8", content type: "application/vnd.apple.mpegurl", previous content type: "application/x-mpegURL" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:20:50 [warn] 177784#177876: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:97
2018/05/29 19:20:50 [warn] 166120#129232: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:20:50 [warn] 166120#129232: duplicate extension "m3u8", content type: "application/vnd.apple.mpegurl", previous content type: "application/x-mpegURL" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:20:50 [warn] 166120#129232: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:97
2018/05/29 19:20:52 [warn] 175800#177592: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:20:52 [warn] 175800#177592: duplicate extension "m3u8", content type: "application/vnd.apple.mpegurl", previous content type: "application/x-mpegURL" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:20:52 [warn] 175800#177592: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:97
2018/05/29 19:20:52 [notice] 175800#177592: signal process started
2018/05/29 19:20:53 [warn] 177420#176752: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:20:53 [warn] 177420#176752: duplicate extension "m3u8", content type: "application/vnd.apple.mpegurl", previous content type: "application/x-mpegURL" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:20:53 [warn] 177420#176752: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:97
2018/05/29 19:20:53 [warn] 178156#177512: duplicate extension "m3u8", content type: "application/x-mpegURL", previous content type: "application/vnd.apple.mpegurl" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:95
2018/05/29 19:20:53 [warn] 178156#177512: duplicate extension "m3u8", content type: "application/vnd.apple.mpegurl", previous content type: "application/x-mpegURL" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:96
2018/05/29 19:20:53 [warn] 178156#177512: duplicate extension "ts", content type: "video/MP2T", previous content type: "video/mp2t" in G:\pyWorkspace\django_work\nginx-1.13.8/conf/mime.types:97
2018/05/29 19:20:55 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/1.txt" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/1.txt HTTP/1.1", host: "localhost"
2018/05/29 19:21:07 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/index" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /index. HTTP/1.1", host: "localhost"
2018/05/29 19:22:05 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg HTTP/1.1", host: "localhost"
2018/05/29 19:22:34 [notice] 178276#178304: signal process started
2018/05/29 19:22:36 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg HTTP/1.1", host: "localhost"
2018/05/29 19:22:37 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg HTTP/1.1", host: "localhost"
2018/05/29 19:22:37 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg HTTP/1.1", host: "localhost"
2018/05/29 19:22:38 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg HTTP/1.1", host: "localhost"
2018/05/29 19:23:00 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg HTTP/1.1", host: "localhost"
2018/05/29 19:23:01 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg HTTP/1.1", host: "localhost"
2018/05/29 19:23:16 [notice] 179088#177884: signal process started
2018/05/29 19:23:20 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg HTTP/1.1", host: "localhost"
2018/05/29 19:23:37 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg HTTP/1.1", host: "localhost"
2018/05/29 19:23:39 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /pic/middle/5b58b532f06f1613c2ecf6f2c0c09230/32b775c0eb7cbc71fe86c943b8843e52.jpg HTTP/1.1", host: "localhost"
2018/05/29 19:23:55 [error] 177504#177348: *52 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/1.txt" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/1.txt HTTP/1.1", host: "localhost"
2018/05/29 19:27:57 [notice] 178100#178000: signal process started
2018/05/29 19:28:16 [notice] 176184#176876: signal process started
2018/05/29 19:28:16 [error] 176184#176876: CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/logs/nginx.pid" failed (2: The system cannot find the file specified)
2018/05/29 19:28:25 [error] 169248#177824: *28 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/1.txt" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/1.txt HTTP/1.1", host: "localhost"
2018/05/29 19:28:26 [error] 169248#177824: *28 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/1.txt" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/1.txt HTTP/1.1", host: "localhost"
2018/05/29 19:28:27 [error] 169248#177824: *28 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/movie/1.txt" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /movie/1.txt HTTP/1.1", host: "localhost"
2018/05/29 19:40:42 [notice] 128700#180172: signal process started
2018/05/29 19:41:41 [error] 169248#177824: *29 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/static/meida/movie/973e6065ce6a65f4c0d544d540b4580f/out.m3u8" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /static/meida/movie/973e6065ce6a65f4c0d544d540b4580f/out.m3u8 HTTP/1.1", host: "localhost", referrer: "http://localhost:909/video/http://192.168.199.124/movie//973e6065ce6a65f4c0d544d540b4580f/out.m3u8/"
2018/05/29 19:42:04 [error] 169248#177824: *29 CreateFile() "G:\pyWorkspace\django_work\nginx-1.13.8/html/static/meida/movie/973e6065ce6a65f4c0d544d540b4580f/out.m3u8" failed (3: The system cannot find the path specified), client: 127.0.0.1, server: localhost, request: "GET /static/meida/movie/973e6065ce6a65f4c0d544d540b4580f/out.m3u8 HTTP/1.1", host: "localhost"
